@include('header')
<style>
   .popular-category1 {
   background: #30e3ca;
   display: block;
   text-align: center;
   padding: 30px 10px;
   border-radius: 7px;
   top: 0;
   position: relative;
   -webkit-transition: .3s all ease-in-out;
   -o-transition: .3s all ease-in-out;
   transition: .3s all ease-in-out;
   color: white!important }
   .popular-category1 .icon {
   display: block;
   -webkit-transition: .1s all ease;
   -o-transition: .1s all ease;
   transition: .1s all ease;
   margin-bottom: 10px; }
   .popular-category1 .icon > span {
   line-height: 0;
   font-size: 45px; }
   .popular-category1 .caption {
   color: #fff;
   -webkit-transition: .1s all ease;
   -o-transition: .1s all ease;
   transition: .1s all ease;
   text-transform: none;
   letter-spacing: normal;
   font-size: 18px;
   font-weight: normal; }
   .popular-category1 .number {
   padding: 2px 20px;
   border-radius: 30px;
   display: inline-block;
   background: #e9ecef;
   color: #000;
   font-size: 14px;
   -webkit-transition: .1s all ease;
   -o-transition: .1s all ease;
   transition: .1s all ease; }
   .popular-category1:hover {
   background: #fff;
   font-color:#30e3ca;
   -webkit-box-shadow: 0 5px 30px -5px rgba(48, 227, 202, 0.5);
   box-shadow: 0 5px 30px -5px rgba(48, 227, 202, 0.5);
   top: -10px; }
   .popular-category1:hover .caption {
   color: #30e3ca; }
   .popular-category1:hover .icon {
   color: #fff; }
   .popular-category1:hover .number {
   background: #1bc5ad;
   color: #fff; }
</style>
<div class="site-wrap">
   
   @include('header_for_single_page')

   <div class=" overlay" style="background-image: url(images/contact.jpg);height:50%!important" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container" style="height: 380px">
         <!-- <iframe width="100%" height="auto" src="https://www.youtube.com/embed/ZBZxQV6JDFI?autoplay=1&muted=1&loop=1&controls=0&rel=0&hd=1&playlist=ZBZxQV6JDFI&showinfo=0&fs=0" title="YouTube video player" frameborder="0"></iframe> -->
         <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-12">
               <div class="row justify-content-center mb-4">
                  <div class="col-md-8 text-center  form-search-wrap" style="margin-top: 15%" >
                     <h1 style="color: black; font-weight: 800" class="" data-aos="fade-up">Terms And Conditions </h1>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="row pt-0">
         <div class="col-12 p-5">
           <p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">By accessing any of the website operated by ProVideoFactory Inc. (hereinafter &ldquo;PVF&rdquo;), you, the user, agree to be bound by all of the terms for service and agree these terms constitute a binding contract between the user and PVF.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">These General Terms of Service apply to all users. Any access to or licensing or use of Content (i.e. any work or other subject matter, including digital files, images, animations, films, audio, video, or audio/visual representations recorded in any format available for Download from the PVF Website), including subscriptions, are governed by the &ldquo;<a href="https://provideofactory.com/legal/license-agreement" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: inherit; text-decoration: inherit; box-shadow: none; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent;">Terms of Use and African Drone Stock Royalty-Free License</a>&rdquo; Agreement (the &ldquo;Agreement&rdquo;). In the event of any inconsistency between the terms of that Agreement and these General Terms of Service, the terms of the Agreement will apply.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Intellectual Property</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">The Website is the property of PVF, and is protected by intellectual property and other laws, including copyright, trademark, patent and trade secret laws. PVF and/or its contributors own all rights, title, and interests in and to the Website and the Content.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><a href="https://provideofactory.com/legal/license-agreement" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: rgb(255, 255, 255); color: inherit; text-decoration: inherit; box-shadow: none; font-weight: var( --e-global-typography-text-font-weight ); border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; outline: 0px !important;">African Drone Stock</a>, AROUND THE WORLD MEDIA S.R.L., and any other trademarks, names, logos or product or service names appearing on the Website are the property of their respective owners and may not be used, copied, imitated, or otherwise dealt with (including by incorporating terms comprising such marks as metatags or &ldquo;hidden text&rdquo;) in the absence of prior written permission from the relevant owner. PVF does not endorse, sponsor or hold out approval of any product, service, process or information referenced on its Website.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">The Website may only be copied for personal, non-commercial purposes. Only the amount necessary for the purpose of your activity may be copied, and it may not be modified in any way, including by removing any intellectual property notice or other rights management information. Notwithstanding, PVF may, in its sole discretion, deem any non-licensed dealings with the Website as infringing or violating PVF&rsquo;s rights, and PVF reserves its rights to challenge and seek damages and other remedies in respect of all such dealings. Except to the extent permitted under the License Agreement, you are prohibited from creating any derivative works from the Website or otherwise exploiting the Website, without PVF&rsquo;s written permission.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">Users may, subject to these General Terms of Service and the Agreement, print or otherwise save individual pages for private use. However, and subject to the terms of the Agreement, the contents of this Website, including the Content and all related information, may not be modified or altered in any respect, merged with other data or published in any form, in whole or in part. The prohibited uses include &ldquo;screen scraping&rdquo;, &ldquo;database scraping&rdquo; and any other activity intended to collect, store, reorganize or manipulate videos and data on the pages produced by, or displayed on the Website.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Links to Website</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">Users may link to the Website. However, PVF reserves the right to refuse a link at any time at PVF&rsquo;s sole discretion. The user agrees to remove any link to the Website at PVF&rsquo;s request. The link must result in a new, fully functional, full screen browser window occupied solely by the pages created by the PVF Website.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Links to Third Party Sites</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">Links to third party websites, materials, or services posted on the Website are for your convenience only. PVF does not control such third party websites or materials, or any third party goods or services accessible or offered through such links. The display of links to third party websites, materials, goods or services on the Website does not imply PVF&rsquo;s monitoring or endorsement thereof, or that the links are live and accurate. You should review the Terms Of Use and Privacy Policies on such third party websites before proceeding to use them.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Frames</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">Users and third parties may not under any circumstance use technology to display the content of PVF&rsquo;s websites, including Content, in a frame or in any other manner that is different from how it would appear if a user typed the URL into the browser line.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Privacy</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">The user acknowledges that their personal information will be used by the website in accordance with the <a href="https://provideofactory.com/legal/privacy-policy" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: inherit; text-decoration: inherit; box-shadow: none; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent;">website privacy policy</a></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Liability and Warranty Disclaimer</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">The Website, PVF&rsquo;s services, Content, and any Content information (including keywords, captions, categorizations, titles, and descriptions), are provided &ldquo;as is&rdquo; without any kind of representation, warranty or condition of any kind, either expressly or implied, including any implied warranties of merchantability, fitness for a particular purpose, non-infringement, quiet enjoyment, or title. PVF makes no representation or warranty that information contained in the Website is accurate, current, or complete. PVF further disclaims any representation or warranty that the Website, Content, or Content information will meet your requirements, is compatible with any particular hardware, software, device, or operating system, or that use of the Website or Content will be uninterrupted or error free. The Website and all Content is accessed at your own risk. You acknowledge that you shall be solely responsible for any loss or damage to your property or person, including but not limited to, your computer system and any hardware, software, or device used to access the Website, PVF&rsquo;s services or Content or Content Information. Certain jurisdictions do not allow the exclusion of implied warranties, and your rights may vary from jurisdiction to jurisdiction.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">No Waiver</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">PVF&rsquo;s failure or delay to enforce any of the terms and conditions under these General Terms of Service shall not operate as a waiver of any of PVF&rsquo;s rights or privileges under these General Terms of Service.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Termination of Access</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">PVF reserves the right, in its sole discretion, to terminate, limit or suspend any user&rsquo;s access to the Website without notice or liability, for any reason whatsoever, including the user&rsquo;s breach of any of these General Terms of Service.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">Updates, Upgrades and Revisions</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">PVF may update, revise, supplement or delete information, services, resources, and/or Content contained on the Website, as well as these General Terms of Service, from time to time, and reserves its right to do so without prior notice to you. Any changes will be posted on the PVF Website. Changes are effective immediately upon being posted to the website, and your continued use of the Website shall constitute your acceptance of such changes. You should check these General Terms of Service regularly to update yourself on any changes.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Language</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">If these General Terms of Service are translated into a language other than English and there are conflicts between the translations, the English version shall prevail and control.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">No Assignment</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">You are not permitted to assign or otherwise transfer partially or totally your rights and obligations under these General Terms of Service.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Interpretation</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">These General Terms of Service shall be interpreted without regard to which party drafted these General Terms of Service.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Severability</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">If any of the provisions of these General Terms of Service are held invalid or unenforceable, such a finding will not affect the validity of any other provisions of these General Terms of Service , unless the invalidity or unenforceability would invalidate the remainder of these General Terms of Service.</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; font-weight: bolder;">Governing Law</span></p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px 0px 1rem; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border: 0px solid rgb(229, 231, 235); --tw-shadow:0 0 transparent; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; color: rgb(0, 0, 0); font-family: Inter, sans-serif; text-align: justify; background-color: rgb(249, 249, 249);">These General Terms of Service shall be governed by the laws of The Republic of Ghana. The Supreme courts in Ghana will have exclusive jurisdiction to hear and decide any disputes relating to these General Terms of Service.</p>
         </div>
      </div >
   </div>
   @include('footer')
</div>
<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.1.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.stellar.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/jquery.magnific-popup.min.js"></script>
<script src="js/bootstrap-datepicker.min.js"></script>
<script src="js/aos.js"></script>
<script src="js/rangeslider.min.js"></script>
<script src="js/main.js"></script>
</body>
<script>
   $(document).ready(function() {
   $(".myvideos").on("mouseover", function(event) {
   this.play();
   
   }).on('mouseout', function(event) {
   this.pause();
   this.currentTime = 0;
   
   });
   })
   
   var vid = document.getElementsByTagName("video");
   [].forEach.call(vid, function (item) {
   item.addEventListener('mouseover', hoverVideo, false);
   item.addEventListener('mouseout', hideVideo, false);
   });
   
   function hoverVideo(e)
   {
   this.play();
   }
   function hideVideo(e)
   {
   this.pause();
   }
</script>
</html>